# Generated by Django 3.1.3 on 2020-11-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degr', models.CharField(blank=True, choices=[('Dr.', 'Dr.'), ('Prof.Dr.', 'Prof.Dr.'), ('Prof.', 'Prof.')], max_length=40)),
                ('fname', models.CharField(blank='NOT ALLOTED', default=True, max_length=40)),
                ('lname', models.CharField(blank=True, default=True, max_length=40)),
                ('department', models.CharField(choices=[('cse', 'CSE'), ('mech', 'MECH'), ('civil', 'CIVIL'), ('auto', 'AUTO')], max_length=40, null=True)),
                ('email', models.CharField(blank=True, default=None, max_length=50)),
                ('mobile', models.CharField(blank=True, default=None, max_length=50)),
                ('username', models.CharField(blank=True, default=None, max_length=50)),
                ('password', models.CharField(blank=True, default=None, max_length=50)),
            ],
        ),
    ]
