# Generated by Django 3.1.3 on 2020-11-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=40)),
                ('fname', models.CharField(blank='NOT ALLOTED', default=True, max_length=40)),
                ('lname', models.CharField(blank=True, default=True, max_length=40)),
                ('department', models.CharField(choices=[('cse', 'CSE'), ('mech', 'MECH'), ('civil', 'CIVIL'), ('auto', 'AUTO')], max_length=40, null=True)),
                ('email', models.CharField(blank=True, default=None, max_length=50)),
                ('mobile', models.CharField(blank=True, default=None, max_length=50)),
                ('username', models.CharField(blank=True, default=None, max_length=50)),
                ('password', models.CharField(blank=True, default=None, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='guide',
        ),
    ]
